name: discord-issue-linked
on:
  issues:
    types: [labeled]
jobs:
  discord-issue-linked:
    if: ${{ github.event.label.name == 'Linked [AC]' }}
    runs-on: ubuntu-latest
    steps:
      - name: Set json
        id: json
        run: |
          TEMPLATE='[{"title": $title, "url": $url, "color": $color, "description": $desc}]'
          echo "DISCORD_EMBEDS=$(jq -nc --arg title "${{ github.event.issue.title }}" --arg url "${{ github.event.issue.html_url }}" --arg color "14649120" --arg desc "The user [${{ github.event.sender.login }}](${{ github.event.sender.html_url }}) has linked the issue to the AC Repo" "$TEMPLATE")" >> $GITHUB_ENV
      - name: Discord notification
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        uses: Ilshidur/action-discord@0.3.0
